//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieMVC.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Movy
    {
        public int Id { get; set; }
        [Display(Name = "Название")]
        public string Title { get; set; }
        [Display(Name = "Описание")]
        public string Description { get; set; }
        [Display(Name = "Год")]
        public int Year { get; set; }
        public string Inserted_UserId { get; set; }
        public System.DateTime Inserted_Date { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        [Display(Name = "Обложка")]
        public byte[] Poster { get; set; }
        [Display(Name = "Режисер")]
        public string Producer { get; set; }

        public virtual User User { get; set; }
    }
}
